spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
      ansi:
          enabled: ALWAYS
  application:
      name: carimbai
carimbai:
  hmac-secret: ${CARIMBAI_HMAC_SECRET}
  stamps-needed: 10
  stamps-default-needed: 10
  rate-limit:
    seconds: 120
  qr-ttl:
    seconds: 90
  jwt:
    secret: ${CARIMBAI_JWT_SECRET}
    expiration-seconds: 28800